channels:
- conda-forge
dependencies:
- python =3.11
- gensim =4.3.3
- nltk =3.9.1
- matplotlib-base =3.10.1
- scikit-learn =1.6.1
- pandas =2.2.3
- bayesian-optimization =2.0.3
- scikit-image =0.25.2
- scipy =1.15.2
- opencv =4.11.0
- py-opencv =4.11.0
- python-ternary =1.0.8
- seaborn =0.13.2
